use bevy::prelude::Color;

pub const SQUARE_SIZE: f32 = 30.;

const WINDOW_HEIGHT: f32 = 30.;
const WINDOW_WIGTH: f32 = 30.;

pub const DISPLAY_WINDOW_HEIGHT: f32 = SQUARE_SIZE*WINDOW_HEIGHT;
pub const DISPLAY_WINDOW_WIGTH: f32 = SQUARE_SIZE*WINDOW_WIGTH;

const BOARD_HEIGHT: f32 = 20.;
const BOARD_WIGTH: f32 = 10.;

pub const DISPLAY_BOARD_HEIGHT: f32 = SQUARE_SIZE*BOARD_HEIGHT;
pub const DISPLAY_BOARD_WIGTH: f32 = SQUARE_SIZE*BOARD_WIGTH;

pub const BOARD_COLOR: Color = Color::BLACK;

pub const SCORE_FONT_SIZE: f32 = 20.;
const SCORE_POSITION_X: f32 = (BOARD_WIGTH / 2.) + 5.;
const SCORE_POSITION_Y: f32 = (BOARD_HEIGHT / 2.) - 1.;

pub const DISPLAY_SCORE_POSITION_X: f32 = SQUARE_SIZE*SCORE_POSITION_X;
pub const DISPLAY_SCORE_POSITION_Y: f32 = SQUARE_SIZE*SCORE_POSITION_Y;
pub const DISPLAY_LINES_POSITION_Y: f32 = SQUARE_SIZE*(SCORE_POSITION_Y - 1.);

pub const SCORE_COLOR: Color = Color::PURPLE;
